#!/bin/bash

if [ $# \< 1 ]; then echo Usage: mku filename; exit; fi

# default partiton = 1
PARTITION=1
if [ $# \> 1 ]; then PARTITION=$2; fi

#use fresh floppy disk
rm vdisk
cp vdiskCOPY vdisk

VDISK=vdisk
SECTOR=$(sudo ./ptable vdisk $PARTITION)
OFFSET=$(sudo expr $SECTOR \* 512)

echo partition=$PARTITION sector=$SECTOR offset=$OFFSET
#read dummy

sudo mount -o loop,offset=$OFFSET $VDISK /mnt

echo compiling $1.c init.c login.c .....
as86 -o u.o u.s
bcc -c -ansi $1.o $1.c
bcc -c -ansi init.o init.c
bcc -c -ansi login.o login.c

echo linking .......
ld86 u.o $1.o init.o login.o mtxlib /usr/lib/bcc/libc.a 

echo copying $1 into $VDISK/bin/$1

sudo cp -av a.out /mnt/bin/$1
sudo umount /mnt

echo done $1
